/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Speaker */

#ifndef _Included_Speaker
#define _Included_Speaker
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     Speaker
 * Method:    sayHi
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_Speaker_sayHi
  (JNIEnv *, jobject);

/*
 * Class:     Speaker
 * Method:    sayBye
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_Speaker_sayBye
  (JNIEnv *, jobject);

/*
 * Class:     Speaker
 * Method:    doStuff
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_Speaker_doStuff
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
